[package]
name = "axklib"
version = "0.2.0"
edition = "2024"
authors = ["周睿 <zrufo747@outlook.com>"]
description = "Small kernel-helper abstractions used across the microkernel"
repository = "https://github.com/arceos-hypervisor/axklib"
license = "Apache-2.0"
keywords = ["arceos", "kernel"]
categories = ["os", "no-std"]
readme = "README.md"
documentation = "https://arceos-hypervisor.github.io/axklib"

[dependencies]
axerrno = "0.1"
memory_addr = "0.4"
trait-ffi = "0.2"
